"""
Django settings for education_khoj project.

Generated by 'django-admin startproject' using Django 4.1.5.
See:
- https://docs.djangoproject.com/en/4.1/topics/settings/
- https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Templates directory
TEMPLATE_DIR = BASE_DIR / "templates"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "***REMOVED***"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["educationkhoj.com", "www.educationkhoj.com", "***REMOVED***"]

# Application definition
INSTALLED_APPS = [
    "Education.apps.EducationConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "django.contrib.sitemaps",
    "django.contrib.sites",

    "tailwind",
    "theme",
    # "django_browser_reload",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "django_extensions",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "django_browser_reload.middleware.BrowserReloadMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

LOGIN_REDIRECT_URL = "home"

ROOT_URLCONF = "education_khoj.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATE_DIR],
        "APP_DIRS": False,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": [
                "django.template.loaders.filesystem.Loader",
                "django.template.loaders.app_directories.Loader",
            ],
        },
    },
]

WSGI_APPLICATION = "education_khoj.wsgi.application"

TAILWIND_APP_NAME = "theme"

# -------------------------------------------------------------------
# Default DATABASES: production (MySQL) – this is what VPS uses
# -------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "users",
        "USER": "root",
        "PASSWORD": "***REMOVED***",
        "HOST": "localhost",
        "PORT": "3306",
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# On the LOCAL machine I have created education_khoj/local_settings.py
# with a SQLite override, e.g.:
#
#   from pathlib import Path
#   from .settings import BASE_DIR
#   DATABASES = {
#       "default": {
#           "ENGINE": "django.db.backends.sqlite3",
#           "NAME": BASE_DIR / "db.sqlite3",
#       }
#   }
#
# and that will NOT affect the VPS as long as it's not uploaded local_settings.py.

NPM_BIN_PATH = r"C:/Program Files/nodejs/npm.cmd"

INTERNAL_IPS = [
    "127.0.0.1",
]

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    "allauth.account.auth_backends.AuthenticationBackend",
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "APP": {
            "client_id": "***REMOVED***",
            "secret": "***REMOVED***",
            "key": "***REMOVED***",
        },
    }
}

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "Education.User_Member"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "ishaaninfomedia@gmail.com"
EMAIL_HOST_PASSWORD = "***REMOVED***"

APPEND_SLASH = True

SITE_ID = 1 

# -------------------------------------------------------------------
STATIC_ROOT = '/var/www/ek/staticfiles/'

# -------------------------------------------------------------------
# Local overrides (only used on your PC)
# -------------------------------------------------------------------
try:
    from .local_settings import *  # noqa
except ImportError:
    pass
