# Generated by Django 4.2.16 on 2025-03-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_member',
            name='first_update_done',
            field=models.BooleanField(default=False),
        ),
    ]
