# Generated by Django 4.2.16 on 2026-03-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0004_footer_section'),
        ('Education', '0006_alter_news_desc'),
    ]

    operations = [
    ]
