# Generated by Django 4.2.16 on 2026-03-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0007_merge_0004_footer_section_0006_alter_news_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer_Section',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='user_member',
            name='first_update_done',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
