# Generated by Django 4.2.16 on 2026-03-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0008_delete_footer_section_remove_galleryimage_gallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('footer_link', models.CharField(default='', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.CharField(default=1, max_length=250)),
            ],
        ),
    ]
