# Generated by Django 4.2.16 on 2026-03-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0009_footer_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer_Section',
        ),
    ]
